name: breaktest
description: App to prevent breaking changes in `hydrated_bloc`

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_bloc: ^5.0.0
  hydrated_bloc:
    path: ../

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
